version: '3'

services: 
  diabet_elastic:
  diabet_kibana:
  diabet_mongo:
  
  backend:
    volumes: 
      - ./src:/app/src

  diabet-nginx: 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes: 
  elastic:
  mongo:

networks: 
  diabet-private-net:
  diabet-public-net:

  
