version: '3'

services: 
  diabet_elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    restart: on-failure
    container_name: diabet_elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=diabet_notes
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - diabet-private-net
  diabet_kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: diabet_kibana
    restart: on-failure
    ports:
      - 5601:5601
    depends_on:
      - diabet_elastic
    environment:
      - ELASTICSEARCH_HOSTS=http://diabet_elastic:9200
    networks:
      - diabet-private-net
      - diabet-public-net

  diabet_mongo:
    image: mongo:latest
    container_name: diabet_mongo
    volumes:
      - mongo:/data/db
    networks: 
      - diabet-private-net

  backend:
    build: . 
    container_name: diabet_backend
    restart: on-failure
    environment: 
      - PORT=9000
      - NODE_ENV=prod
      - MAIL_SERVICE=${MAIL_SERVICE}
      - USER_MAIL=${USER_MAIL}
      - USER_MAIL_PASSWORD=${USER_MAIL_PASSWORD}
    depends_on: 
      - diabet_mongo
      - diabet_elastic
    networks: 
      - diabet-private-net

  diabet-nginx: 
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    container_name: diabet-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9001:9001
    networks: 
      - diabet-private-net
      - diabet-public-net

volumes: 
  elastic:
  mongo:

networks: 
  diabet-private-net:
  diabet-public-net:

  
